Fix GitHub Actions workflow

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -41,6 +41,9 @@ jobs:
       - name: Set Gradle permissions
         run: chmod +x ./gradlew
 
+      - name: "detekt"
+        uses: natiginfo/action-detekt-all@1.23.8
+
 #      - name: Run Detekt
 #        run: ./gradlew detekt --continue
 #
@@ -64,17 +67,16 @@ jobs:
 #        env:
 #          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.REVIEWDOG_TOKEN }}
 
-      - name: Run Unit Tests
-        if: success() || failure()
-        run: ./gradlew test --continue
-
-      - name: Unit Test Report
-        if: success() || failure()
-        uses: dorny/test-reporter@v1
-        with:
-          fail-on-error: false
-          fail-on-empty: false
-          name: Unit Tests
-          path: '**/build/test-results/test*/TEST-*.xml'
-          reporter: java-junit
-          token: ${{ secrets.GITHUB_TOKEN  }}
+#      - name: Run Unit Tests
+#        if: success() || failure()
+#        run: ./gradlew test --continue
+#
+#      - name: Unit Test Report
+#        if: success() || failure()
+#        uses: dorny/test-reporter@v1
+#        with:
+#          fail-on-empty: false
+#          name: Unit Tests
+#          path: '**/build/test-results/test*/TEST-*.xml'
+#          reporter: java-junit
+#          token: ${{ secrets.GITHUB_TOKEN  }}
